name: Duncan.wf
title: Duncan.wf | my website
description:  Duncan.wf is an attempt to make a working website to share images with my friends.
tags:
  - Duncan
  - website
  - memes
  - images
  - posts
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: youremail@test.com
# See: https://disqus.com/
disqus_username: disqus_username
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: "xzzdogzk"
